#pragma once


enum class SCENE_ID { LOGO, MENU, EDIT, STAGE_01, STAGE_RE, STAGE_CLEAR, END };
enum class OBJ_TYPE { PLAYER, EGG, NONE_BLOCK, NORMAL_BLOCK, MOVE_BLOCK, SIDE_BLOCK, PASS_BLOCK, PATTERN_BLOCK, TRANSPARENT_BLOCK, BULLDOG, WOLF, END };
enum class TILE_TYPE { NONE, NORMAL_BLOCK, MOVE_BLOCK, SIDE_BLOCK, PASS_BLOCK, PATTERN_BLOCK, TRANSPARENT_BLOCK };
enum class COL_DIR { LEFT, TOP, RIGHT, BOTTOM, END };
enum class DIRECTION { LEFT, UP, RIGHT, DOWN, LU, RU, END };
enum class STATE { IDLE, WALK, ATTCK, HIT, DEAD, DANCE, END};
enum class RENDERID { BACKGROUND, WOLF_OBJECT, PLAYER_OBJECT, EGG_OBJECT, RE_BACKGROUND , GAMEOBJECT, EFFECT, UI, END };

enum class  BLOCK_STATE{ DELETE_BLOCK, USING_BLOCK, END };
enum class FONT_TYPE { DEFAULT, END };

enum CHANNELID { SOUND_EFFECT, SOUND_BGM, JUMP_SOUND, ATTACK_SOUND, HIT_SOUND, MOVEBLOCK_SOUND, PATTERN_OR_PASS, EGG_DROP, EGG_DIE, MAXCHANNEL};